services:
  piko-1:
    image: ghcr.io/andydunstall/piko:latest
    restart: unless-stopped
    command:
      - server
      - --config.path
      - /etc/piko.yaml
      - --cluster.node-id-prefix
      - piko-1-
    hostname: piko-1
    volumes:
      - ./config/piko.yaml:/etc/piko.yaml
    networks:
      - piko-internal

  piko-2:
    image: ghcr.io/andydunstall/piko:latest
    restart: unless-stopped
    command:
      - server
      - --config.path
      - /etc/piko.yaml
      - --cluster.node-id-prefix
      - piko-2-
    hostname: piko-2
    volumes:
      - ./config/piko.yaml:/etc/piko.yaml
    networks:
      - piko-internal

  piko-3:
    image: ghcr.io/andydunstall/piko:latest
    restart: unless-stopped
    command:
      - server
      - --config.path
      - /etc/piko.yaml
      - --cluster.node-id-prefix
      - piko-3-
    hostname: piko-3
    volumes:
      - ./config/piko.yaml:/etc/piko.yaml
    networks:
      - piko-internal

  load-balancer:
    build: ./caddy
    restart: unless-stopped
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    depends_on:
      - "piko-1"
      - "piko-2"
      - "piko-3"
    ports:
     - "443:443"
     - "443:443/udp"
    networks:
      - piko-internal

  proxy-server:
    build: ./piko-server
    restart: unless-stopped
    ports:
      - 3000
    environment:
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
    depends_on:
      - load-balancer
    networks:
      - piko-internal

  # prometheus:
  #   image: prom/prometheus:latest
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.yml
  #     - --log.level=error
  #   volumes:
  #     - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
  #   depends_on:
  #     - "piko-1"
  #     - "piko-2"
  #     - "piko-3"
  #   ports:
  #     - 9090:9090

  # grafana:
  #   image: grafana/grafana:latest
  #   environment:
  #     - GF_LOG_MODE=console
  #     - GF_LOG_LEVEL=critical
  #   ports:
  #     - 3000:3000

networks:
  piko-internal:
    driver: bridge
    name: piko-internal